#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

echo "::group::Post Review"

OWNER="${GITHUB_REPOSITORY%%/*}"
REPO="${GITHUB_REPOSITORY##*/}"
OUTPUT_FILE="$ARTIFACT_DIR/pipeline-output.json"

if [[ ! -f "$OUTPUT_FILE" ]]; then
  echo "ERROR: No pipeline output — posting fail-closed review"
  gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" \
    -f event="REQUEST_CHANGES" \
    -f body="<!-- pr-code-review-validator -->
## REVIEW ERROR — Pipeline Crash

The code review pipeline failed to produce output. This PR is blocked until the pipeline runs successfully.

**Error:** No output file generated. Check workflow logs for details.

---
*This review was generated by the PR Code Review Validator.*" \
    --silent
  exit 1
fi

if ! jq -e '.verdict' "$OUTPUT_FILE" > /dev/null 2>&1; then
  echo "ERROR: Invalid pipeline output — posting fail-closed review"
  gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" \
    -f event="REQUEST_CHANGES" \
    -f body="<!-- pr-code-review-validator -->
## REVIEW ERROR — Invalid Output

The code review pipeline produced output that could not be parsed. This PR is blocked until the pipeline runs successfully.

**Error:** Output missing 'verdict' field or invalid JSON.

---
*This review was generated by the PR Code Review Validator.*" \
    --silent
  exit 1
fi

verdict=$(jq -r '.verdict' "$OUTPUT_FILE")
summary=$(jq -r '.summary' "$OUTPUT_FILE")
inline_comments=$(jq -c '.inline_comments // []' "$OUTPUT_FILE")
inline_count=$(echo "$inline_comments" | jq 'length')

echo "Verdict: $verdict, Inline comments: $inline_count"

pr_diff_files=$(gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/files" --paginate | jq -r '.[].filename')
if [[ -n "$pr_diff_files" ]]; then
  pr_files_json=$(echo "$pr_diff_files" | jq -R -s 'split("\n") | map(select(length > 0))')
  inline_comments=$(echo "$inline_comments" | jq --argjson valid "$pr_files_json" '[.[] | select(.path as $p | ($valid | index($p)) != null)]')
  inline_count=$(echo "$inline_comments" | jq 'length')
  echo "After path filter: $inline_count inline comments"
fi

review_event="COMMENT"
if [[ "$verdict" == "fail" ]]; then
  review_event="REQUEST_CHANGES"
fi

post_succeeded=false

if [[ "$inline_count" -gt 0 ]]; then
  review_payload=$(jq -n \
    --arg event "$review_event" \
    --arg body "$summary" \
    --arg sha "$HEAD_SHA" \
    --argjson comments "$inline_comments" \
    '{
      event: $event,
      body: $body,
      commit_id: $sha,
      comments: $comments
    }')

  echo "Posting review with $inline_count inline comments..."
  if echo "$review_payload" | gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" \
    --input - --silent 2>/dev/null; then
    post_succeeded=true
    echo "Review posted successfully with inline comments"
  else
    echo "WARNING: Review with comments failed (likely path/line mismatch)"
    latest_reviews=$(gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" --jq '.[0]' 2>/dev/null || echo "{}")
    latest_state=$(echo "$latest_reviews" | jq -r '.state // ""')
    if [[ "$latest_state" == "PENDING" ]]; then
      latest_id=$(echo "$latest_reviews" | jq -r '.id')
      gh api -X DELETE "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews/$latest_id" --silent 2>/dev/null || true
    fi

    echo "Falling back to body-only review..."
    fallback_body="$summary"
    gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" \
      -f event="$review_event" \
      -f body="$fallback_body" \
      -f commit_id="$HEAD_SHA" \
      --silent
    post_succeeded=true
    echo "Body-only review posted (fallback)"
  fi
else
  gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" \
    -f event="$review_event" \
    -f body="$summary" \
    -f commit_id="$HEAD_SHA" \
    --silent
  post_succeeded=true
  echo "Body-only review posted"
fi

if [[ "$verdict" == "pass" || "$verdict" == "skip" ]]; then
  echo "Dismissing any lingering REQUEST_CHANGES reviews..."
  BOT_LOGIN="github-actions[bot]"
  reviews=$(gh api "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews" --paginate 2>/dev/null || echo "[]")
  echo "$reviews" | jq -r --arg bot "$BOT_LOGIN" \
    '.[] | select(.user.login == $bot and .state == "CHANGES_REQUESTED") | .id' | \
  while IFS= read -r review_id; do
    [[ -z "$review_id" ]] && continue
    gh api -X PUT "repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews/$review_id/dismissals" \
      -f message="Review passed — violations resolved" \
      --silent 2>/dev/null || true
  done
fi

echo "Writing violations artifact..."
active_violations=$(echo "$inline_comments" | jq --arg push "${PUSH_COUNT:-1}" '[.[] | {
  path: .path,
  line: .line,
  skill: ((.body | capture("\\*\\*(?<s>[^>]+) >") | .s) // "unknown"),
  rule: ((.body | capture("> (?<r>[^*]+)\\*\\*") | .r) // "unknown"),
  description: "",
  suggestion: "",
  found_in_push: ($push | tonumber),
  body: .body
}]')

jq -n \
  --argjson pr "$PR_NUMBER" \
  --arg sha "$HEAD_SHA" \
  --argjson push "${PUSH_COUNT:-1}" \
  --argjson violations "$active_violations" \
  '{
    pr_number: $pr,
    last_push_sha: $sha,
    push_count: $push,
    active_violations: $violations
  }' > "$ARTIFACT_FILE"

echo "Artifact written: $(jq '.active_violations | length' "$ARTIFACT_FILE") violations"
echo "::endgroup::"

if [[ "$verdict" == "fail" ]]; then
  echo "::error::Code review found violations — PR blocked"
  exit 1
else
  echo "Review complete — $verdict"
  exit 0
fi
