#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/json-extract.sh"

REPO_ROOT="$(git rev-parse --show-toplevel)"
SKILLS_DIR=".claude/skills"
OUTPUT_FILE="$ARTIFACT_DIR/pipeline-output.json"
PROMPTS_DIR="$REPO_ROOT/prompts"

mkdir -p "$ARTIFACT_DIR"

echo "::group::Review Pipeline ($REVIEW_MODE mode)"

run_full_pipeline() {
  local code_files="$1"
  local file_count
  file_count=$(echo "$code_files" | jq 'length')

  if [[ "$file_count" -eq 0 ]]; then
    cat > "$OUTPUT_FILE" <<'SKIPJSON'
{
  "verdict": "skip",
  "summary": "<!-- pr-code-review-validator -->\n## REVIEW SKIPPED — no code files changed\n\nOnly non-code files were modified in this PR. No skill-based review needed.\nStatus: **PASSED**\n\n---\n*This review was generated by the PR Code Review Validator.*",
  "inline_comments": [],
  "stats": {"files_checked":0,"files_changed":0,"files_related":0,"skills_applied":[],"violations_found":0,"false_positives_filtered":0}
}
SKIPJSON
    echo "No code files — skipping"
    return 0
  fi

  if [[ "$file_count" -gt 50 ]]; then
    gh pr comment "$PR_NUMBER" --body "<!-- pr-code-review-validator -->
> **Warning:** This PR changes $file_count code files. Review may take longer than usual." 2>/dev/null || true
  fi

  local file_list
  file_list=$(echo "$code_files" | jq -r '.[]')
  local prompt
  prompt=$(cat "$PROMPTS_DIR/pipeline-full.md")
  prompt="${prompt//\{\{CHANGED_FILES\}\}/$file_list}"
  prompt="${prompt//\{\{SKILLS_DIR\}\}/$SKILLS_DIR}"
  prompt="${prompt//\{\{HEAD_SHA\}\}/$HEAD_SHA}"

  local prompt_file="$ARTIFACT_DIR/prompt-full.txt"
  echo "$prompt" > "$prompt_file"

  local raw_output="$ARTIFACT_DIR/raw-output-full.json"
  local stderr_log="$ARTIFACT_DIR/cli-stderr.log"
  echo "Invoking Claude Code CLI (model: $MODEL_CLASSIFY, timeout: ${TIMEOUT_FULL_PIPELINE}s)..."
  echo "DEBUG: ANTHROPIC_BEDROCK_BASE_URL=${ANTHROPIC_BEDROCK_BASE_URL:-unset}"
  echo "DEBUG: CLAUDE_CODE_USE_BEDROCK=${CLAUDE_CODE_USE_BEDROCK:-unset}"
  echo "DEBUG: CLAUDE_CODE_SKIP_BEDROCK_AUTH=${CLAUDE_CODE_SKIP_BEDROCK_AUTH:-unset}"
  echo "DEBUG: ANTHROPIC_CUSTOM_HEADERS=${ANTHROPIC_CUSTOM_HEADERS:-unset}"
  if ! timeout "$TIMEOUT_FULL_PIPELINE" claude --print --model "$MODEL_CLASSIFY" --output-format json < "$prompt_file" > "$raw_output" 2>"$stderr_log"; then
    echo "ERROR: CLI invocation failed or timed out"
    echo "--- stderr output ---"
    cat "$stderr_log" || true
    echo "--- raw output (first 500 chars) ---"
    head -c 500 "$raw_output" || true
    echo ""
    return 1
  fi

  if ! extract_json "$raw_output" "$OUTPUT_FILE"; then
    echo "ERROR: Failed to extract valid JSON from CLI output"
    return 1
  fi

  echo "--- extracted output (first 1000 chars) ---"
  head -c 1000 "$OUTPUT_FILE" || true
  echo ""
  echo "--- raw CLI output (first 1000 chars) ---"
  head -c 1000 "$raw_output" || true
  echo ""

  if ! jq -e '.verdict' "$OUTPUT_FILE" > /dev/null 2>&1; then
    echo "ERROR: Output missing 'verdict' field"
    return 1
  fi

  echo "Pipeline complete: verdict=$(jq -r '.verdict' "$OUTPUT_FILE")"
}

run_incremental_pipeline() {
  local track1_files="$1"
  local track2_files="$2"
  local prior_violations="$3"
  local untouched_violations="$4"

  local track1_count track2_count
  track1_count=$(echo "$track1_files" | jq 'length')
  track2_count=$(echo "$track2_files" | jq 'length')
  local total_code_files=$((track1_count + track2_count))

  if [[ "$total_code_files" -eq 0 ]]; then
    local untouched_count
    untouched_count=$(echo "$untouched_violations" | jq 'length')
    if [[ "$untouched_count" -gt 0 ]]; then
      build_incremental_output "fail" "[]" "$untouched_violations" "[]"
    else
      build_incremental_output "pass" "[]" "[]" "[]"
    fi
    return 0
  fi

  local track1_result="[]"
  if [[ "$track1_count" -gt 0 ]]; then
    echo "Track 1: Verifying $track1_count files with prior violations..."
    local prompt
    prompt=$(cat "$PROMPTS_DIR/verification-track1.md")
    prompt="${prompt//\{\{PRIOR_VIOLATIONS_JSON\}\}/$prior_violations}"

    local prompt_file="$ARTIFACT_DIR/prompt-track1.txt"
    echo "$prompt" > "$prompt_file"

    local raw_output="$ARTIFACT_DIR/raw-output-track1.json"
    if timeout "$TIMEOUT_TRACK1_VERIFY" claude --print --model "$MODEL_VALIDATE" --output-format json < "$prompt_file" > "$raw_output"; then
      local extracted="$ARTIFACT_DIR/extracted-track1.json"
      if extract_json "$raw_output" "$extracted" && jq -e '.verified' "$extracted" > /dev/null 2>&1; then
        track1_result=$(jq -c '.verified' "$extracted")
        echo "Track 1 complete: $(echo "$track1_result" | jq '[.[] | select(.status == "still_present")] | length') still present"
      else
        echo "WARNING: Track 1 extraction failed — assuming all still_present"
        track1_result=$(echo "$prior_violations" | jq -c '[to_entries[] | {id: .key, status: "still_present", path: .value.path, line: .value.line, reason: "Verification failed — assumed still present"}]')
      fi
    else
      echo "WARNING: Track 1 timed out — assuming all still_present"
      track1_result=$(echo "$prior_violations" | jq -c '[to_entries[] | {id: .key, status: "still_present", path: .value.path, line: .value.line, reason: "Verification timed out — assumed still present"}]')
    fi
  fi

  local track2_violations="[]"
  if [[ "$track2_count" -gt 0 ]]; then
    echo "Track 2: Validating $track2_count new files..."
    local file_list
    file_list=$(echo "$track2_files" | jq -r '.[]')
    local prompt
    prompt=$(cat "$PROMPTS_DIR/pipeline-incremental-track2.md")
    prompt="${prompt//\{\{TRACK2_FILES\}\}/$file_list}"
    prompt="${prompt//\{\{SKILLS_DIR\}\}/$SKILLS_DIR}"
    prompt="${prompt//\{\{HEAD_SHA\}\}/$HEAD_SHA}"

    local prompt_file="$ARTIFACT_DIR/prompt-track2.txt"
    echo "$prompt" > "$prompt_file"

    local raw_output="$ARTIFACT_DIR/raw-output-track2.json"
    if timeout "$TIMEOUT_FULL_PIPELINE" claude --print --model "$MODEL_CLASSIFY" --output-format json < "$prompt_file" > "$raw_output"; then
      local extracted="$ARTIFACT_DIR/extracted-track2.json"
      if extract_json "$raw_output" "$extracted" && jq -e '.verdict' "$extracted" > /dev/null 2>&1; then
        track2_violations=$(jq -c '.inline_comments // []' "$extracted")
        echo "Track 2 complete: $(echo "$track2_violations" | jq 'length') violations"
      else
        echo "ERROR: Track 2 extraction failed"
        return 1
      fi
    else
      echo "ERROR: Track 2 timed out"
      return 1
    fi
  fi

  build_incremental_output "" "$track1_result" "$untouched_violations" "$track2_violations"
}

build_incremental_output() {
  local forced_verdict="$1"
  local track1_result="$2"
  local untouched_violations="$3"
  local track2_inline="$4"

  local prior_violations_arr
  prior_violations_arr=$(echo "${PRIOR_VIOLATIONS_JSON}" | jq -c '.')
  local still_present_violations
  still_present_violations=$(echo "$track1_result" | jq -c --argjson prior "$prior_violations_arr" \
    '[.[] | select(.status == "still_present") | . as $v | $prior[$v.id] | .line = $v.line]' 2>/dev/null || echo "[]")

  local all_active
  all_active=$(jq -n --argjson untouched "$untouched_violations" \
    --argjson still "$still_present_violations" \
    '$untouched + $still')

  local total_violations
  total_violations=$(echo "$all_active" | jq 'length')
  local track2_count
  track2_count=$(echo "$track2_inline" | jq 'length')
  total_violations=$((total_violations + track2_count))

  local verdict
  if [[ -n "$forced_verdict" ]]; then
    verdict="$forced_verdict"
  elif [[ "$total_violations" -eq 0 ]]; then
    verdict="pass"
  else
    verdict="fail"
  fi

  local inline_comments
  inline_comments=$(echo "$all_active" | jq -c '[.[] | {path: .path, line: .line, side: "RIGHT", body: .body}]')
  inline_comments=$(jq -n --argjson existing "$inline_comments" --argjson new "$track2_inline" '$existing + $new')

  local summary
  if [[ "$verdict" == "pass" ]]; then
    summary="<!-- pr-code-review-validator -->\n## REVIEW COMPLETE — PASSED (clean)\n\n| Metric | Value |\n|--------|-------|\n| Review mode | Incremental |\n| Violations found | 0 |\n| Status | **PASSED** |\n\n---\n*This review was generated by the PR Code Review Validator.*"
  else
    summary="<!-- pr-code-review-validator -->\n## REVIEW COMPLETE — VIOLATIONS FOUND (incremental)\n\n| Metric | Value |\n|--------|-------|\n| Review mode | Incremental |\n| Active violations | $total_violations |\n| Status | **BLOCKED** |\n\n---\n*This review was generated by the PR Code Review Validator. All violations must be resolved before merging.*"
  fi

  jq -n \
    --arg verdict "$verdict" \
    --arg summary "$summary" \
    --argjson inline "$inline_comments" \
    --argjson violations_found "$total_violations" \
    '{
      verdict: $verdict,
      summary: $summary,
      inline_comments: $inline,
      stats: {
        files_checked: 0,
        files_changed: 0,
        files_related: 0,
        skills_applied: [],
        violations_found: $violations_found,
        false_positives_filtered: 0
      }
    }' > "$OUTPUT_FILE"

  echo "Incremental merge complete: verdict=$verdict, violations=$total_violations"
}

if [[ "$REVIEW_MODE" == "full" ]]; then
  run_full_pipeline "$CODE_FILES_JSON"
elif [[ "$REVIEW_MODE" == "incremental" ]]; then
  run_incremental_pipeline "$TRACK1_FILES_JSON" "$TRACK2_FILES_JSON" "$PRIOR_VIOLATIONS_JSON" "$UNTOUCHED_VIOLATIONS_JSON"
else
  echo "ERROR: Unknown review mode: $REVIEW_MODE"
  exit 1
fi

echo "::endgroup::"
